workflows:
  version: 2

  test_workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    working-directory: ~/repo
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install coverage
          command: pip install coverage
      - run:
          name: Run tests
          command: |
            TEST_FILES="$(circleci tests glob "tests/_test*.py" | circleci tests split --split-by=timings)"
            coverage run -m pytest $TEST_FILES
      - run:
          name: Coverage report
          command: coverage report


