version: 2

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    parallelism: 2
    executor: python/default
    steps:
      -
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run tests
          command: circleci tests glob **/tests/*.py | circleci tests split --split-by=timings | xargs python -m pytest --reuse-db --junitxml=test_results/results.xml

workflows:
  main:
    jobs:
      - build-and-test