version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install pytest coverage
          name: Install coverage and pytest
      - run:
          command: coverage run -m pytest
          name: Run tests with coverage
      - run:
          command: coverage report
          name: Coverage report

workflows:
  main:
    jobs:
      - build-and-test
